### PR TITLE
🔧 MAINTAIN: Drop furo-specific stylesheet

### PR DESCRIPTION
**Pull request by pradyunsg**
Furo is gonna add styles for supporting this extension directly. This can be merged once I make a Furo release with the relevant changes.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Cross post question: https://github.com/pradyunsg/furo/issues/111#issuecomment-899138969

I don’t see this css in furo yet?

**Comment by pradyunsg** [comment]
@chrisjsewell I'm unlikely to make the change you've asked for in that comment.

As far as I am concerned, this stylesheet is _completely_ wrong, since https://pradyunsg.me/furo/changelog/#beta39. I've overridden everything that this sets in Furo, and if you want sphinx-design to be usable in the current versions of Furo, it'd be best to just straight up drop this stylesheet IMO.

I'll defer to others on whether this should be merged or not. I'll note that if this PR gets rejected, I intend to remove the sphinx-design-specific stylesheets from Furo and also remove the relevant section from Furo's documentation.

**Comment by chrisjsewell** [comment]
> if you want sphinx-design to be usable in the current versions of Furo, it'd be best to just straight up drop this stylesheet IMO.
> if this PR gets rejected, I intend to remove the sphinx-design-specific stylesheets from Furo and also remove the relevant sections recommending/advertising support from Furo's documentation.

I'm a bit surprised by this comment, it feels a bit aggressive, no?

Just to clarify, this stylesheet is not part of the sphinx-design package, it is only used for the internal documentation, i.e. there is nothing for Furo to override unless users specifically choose to add this CSS to their package (outside of using the sphinx-design extension)
So I'm a little unclear why you feel this is such a critical issue?

This is not to say I'm against removing it.
As mentioned pradyunsg/furo#111, the only reason I added it was there were some issues with a few uses of elements in the documentation being visible in both light and dark mode; for example, if you create a black outline button then it is fine in light mode, but effectively invisible in dark mode.
It's a relatively niche case, but it brings in to question what it means to specify a dark/light color in such an adaptive theme

I would have imagined the more critical issue would be #21, which I was still hoping for a reply from you

**Comment by pradyunsg** [comment]
I still do suggest dropping this stylesheet entirely -- having this means that the users don't get a representative view of how the extension will behave in their documentation, which... isn't ideal. :)

**Comment by chrisjsewell** [comment]
Ah yeh no worries, we've all been there lol. I'll try to get this sorted soon 👍

**Comment by pradyunsg** [comment]
You're missing an important detail: there's a dark mode toggle in Furo. :)

**Comment by pradyunsg** [comment]
What's the blockers to merging this again?

**Comment by chrisjsewell** [comment]
> What's the blockers to merging this again?

will circle back around to this soon 😬

**Review by chrisjsewell — APPROVED** [review]
Cheers @pradyunsg, sorry this fell off my radar a bit!

**Comment by pradyunsg** [comment]
No worries, cheers! :)

**Pull request merged**
