### PR TITLE
⬆️ Update Materials Design Icons to v4.0.0-46-gc9e5528

### PR DESCRIPTION
**Pull request by 2bndy5**
This adds 421 icons; some are fresh icons, and some are just different sizes. Threre might be some name changes, but it should be current with what is shown on the https://fonts.google.com/icons (as referenced by this ext's docs).

### CODE REVIEW

**Comment by chrisjsewell** [comment]
thanks, is there some kind of versioning for these icons though?

**Comment by 2bndy5** [comment]
Unfortunately, no. The Google team isn't very forthcoming about the material icons repo. They recently stopped accepting new icons from outside their "inner circle". You may already be aware of the third party MDI node.js pkg(s) because they've given up maintaining that on that end also.

The last release (v4.0.0 long ago) was a huge re-organization of the repo that isn't very Windows friendly.

**Comment by 2bndy5** [comment]
[Huge update](https://github.com/google/material-design-icons/pull/1344) to the material icons repo today. I'll update this PR in accordance (hopefully tomorrow). I'll also add a versioned identifier (probably using SHA in a separate file).

**Comment by 2bndy5** [comment]
OK. I've updated the JSONs using the latest commit from google's MDI repo.

I also added a material-icons_VERSION.txt file that includes:
1. a link to google's repo
2. the abbreviated version (containing the number of commits since tagged)
3. the full SHA of the commit used.

**Comment by chrisjsewell** [comment]
> I also added a material-icons_VERSION.txt file that includes:

thanks for this @2bndy5, sorry I was still differing a little because of the large diff.
I thought it would be nice to know exactly what was had changed, in available icon names.
So I run this before and after your PR, and compared.

```python
data = {}
base = Path("sphinx_design/compiled")
for path in base.glob("material_*.json"):
    mtype = path.name[9:-5]
    for name in json.loads(path.read_text()):
        data.setdefault(name, [])
        data[name].append(mtype)
base.joinpath("names_material.json").write_text(json.dumps(data, indent=2, sort_keys=True))
```

As you can see, there are only additions, which in my book means no breaking changes 👌 

image

**Review by chrisjsewell — APPROVED** [review]
cheers!

**Comment by 2bndy5** [comment]
Again, I wish the Google team was a lot more explanatory about their changes to the icons repo. The last big change was from a PR labeled "update icons" with no description. The merge commit was so large that github couldn't display the diff...

**Pull request merged**
