### PR TITLE
🔧 Add FIPS compliant flag to md5 call

### LINKED ISSUE #161: Add support for FIPS enabled systems
### Describe the bug

**context**
When using the extension on [FIPS](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards)-enabled systems, `hashlib.md5` fails (`update_css_js:70`) due to security reasons.

**expectation**
The hashing should work, independently of FIPS being enabled or not.

**bug**
The following exception is encountered instead:
```bash
Extension error (sphinx_design.extension):
Handler <function update_css_js at 0x7f44aa9b9280> for event 'builder-inited' threw an exception (exception: [digital envelope routines] unsupported)
```

**problem**
This is a problem for users generating documentation on these systems.

**solutions**
Changing the algorithm, or adding `usedforsecurity=Flag` kwarg seems to solve the issue.

```python
hash = hashlib.md5(content.encode("utf8"), usedforsecurity=False).hexdigest()
```

or

```python
hash = hashlib.sha256(content.encode("utf8")).hexdigest()
```

### Reproduce the bug

1. Enable FIPS on your system
2. Try to generate documentation using `sphinx-design`
3. Generation fails

### List your environment

Standard `python-3.9`.

### PR DESCRIPTION
**Pull request by gabor-varga**
Closes #161

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Heya, `usedforsecurity` was only added in Python 3.9 https://docs.python.org/3/library/hashlib.html#hash-algorithms, so some handling for <3.9 needs to be implemented 😄

**Comment by gabor-varga** [comment]
> Heya, `usedforsecurity` was only added in Python 3.9 https://docs.python.org/3/library/hashlib.html#hash-algorithms, so some handling for <3.9 needs to be implemented 😄

Ah indeed, and I thought it was just a nice one-line PR :)

**Comment by chrisjsewell** [comment]
> Ah indeed, and I thought it was just a nice one-line PR

They never are 😂

**Comment by gabor-varga** [comment]
> > Ah indeed, and I thought it was just a nice one-line PR
> 
> They never are 😂

So I am not too proficient with `python`, maybe you can recommend the best solution for this. This seems to be straightforward:

```python
has_usedforsecurity_support = float(sys.version[:3]) >= 3.9
```
Or something with the `inspect` module to check if `md5` function supports the `usedforsecurity` kwargs, although that seems convoluted.

And then just use something like:

```python
kwargs = {"usedforsecurity": False} if has_usedforsecurity_support  else {}
hash = hashlib.md5(content.encode("utf8"), **kwargs ).hexdigest()
```

**Comment by gabor-varga** [comment]
@chrisjsewell do you think this is sufficient? I'll use my fork until the next release.

**Comment by chrisjsewell** [comment]
> @chrisjsewell do you think this is sufficient? I'll use my fork until the next release.

Yep I think it's fine but bare with me to merge

**Review by chrisjsewell — APPROVED** [review]
Sorry for the wait but all good now, and removed 3.9 check as 3.8 was dropped 😄

**Pull request merged**
