### PR TITLE
⬆️ Update Material Design Icons to v4.0.0-116-ge9da21

### PR DESCRIPTION
**Pull request by 2bndy5**
Of the 14155 svg files process,
- 11 new icons added
   - regular/trolley
   - regular/forklift
   - regular/conveyor_belt
   - regular/pallet
   - regular/front_loader
   - regular/assignment_add
   - regular/rebase_edit
   - regular/barcode_reader
   - regular/shelves
   - regular/format_list_bulleted_add
   - regular/movie_edit
- 35 icons have new sizes
- 0 icons' sizes were removed
- 0 icons were replaced or removed

### CODE REVIEW

**Comment by 2bndy5** [comment]
Sorry its been so long since my last update of these icons. The google/material-icons repo grew too large (with non-shallow depth) for normal checkout in the CI runner that generates these JSON files... I had to resort to a sparse checkout to get the correct version tag.

**Comment by 2bndy5** [comment]
codecov action is hitting API rate limit:
> Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1582s.', code='throttled')}

This could be avoided by saving coverage data (.coverage\* files) as artifacts, then using `coverage combine && coverage xml` to upload 1 unified coverage report. I use this tactic in my other py projects' CI
```yml
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r tests/requirements.txt
      - name: Run tests and collect coverage
        # --parallel-mode ensures a unique name for .coverage file
        run: coverage run --parallel-mode -m pytest
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: .coverage*
          name: coverage-data-py${{ matrix.python-version }}
          # .coverage* files are technically hidden hiles
          include-hidden-files: true
  report:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-data-py*
          path: ci-artifacts
      - run: mv ci-artifacts/**/.coverage* ./
      - run: pip install coverage
      - name: Create coverage report
        run: |
          coverage combine
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

**Comment by chrisjsewell** [comment]
> codecov action is hitting API rate limit

Its due to this https://github.com/codecov/codecov-action/issues/1293, I haven't found it matters how little uploads you have, its because you are on a fork.
Will deactivate for forks in a bit for now, as have done for other repos

**Comment by 2bndy5** [comment]
I can rebase the branch if you want

**Comment by 2bndy5** [comment]
Oh, I see you added a regression test. I'll be sure to adhere to this in the future.

**Comment by chrisjsewell** [comment]
yeh no worries, it was something I'd already done for octicons, and makes it clearer in the git diff to check for breaking changes, i.e. removed icons

**Pull request merged**
